name = "ada_librdkafka"
description = "Ada bindings for librdkafka shared library"
version = "0.1.0-dev"

authors = ["Erik Gustafsson"]
maintainers = ["Erik Gustafsson <notputtingmyemailhere@example.com>"]
licenses = "MIT"
website = "https://github.com/erikgust2/ada-librdkafka"
tags = ["kafka", "bindings", "librdkafka"]
